'use strict';
console.log('Задание 2');
const total=100;
let ordered=50;
console.log(ordered>total?"На складе недостаточно твоаров!":"Заказ оформлен, с вами свяжется менеджер");
ordered=20;
console.log(ordered>total?"На складе недостаточно твоаров!":"Заказ оформлен, с вами свяжется менеджер");
ordered=80;
console.log(ordered>total?"На складе недостаточно твоаров!":"Заказ оформлен, с вами свяжется менеджер");
ordered=130;
console.log(ordered>total?"На складе недостаточно твоаров!":"Заказ оформлен, с вами свяжется менеджер");
